# Generated by Django 4.2.6 on 2023-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
