# Generated by Django 4.2.6 on 2023-11-08 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 10, 56, 7, 27740)),
        ),
    ]
