# Generated by Django 4.2.6 on 2023-11-10 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 12, 20, 1, 353529)),
        ),
    ]
