# Generated by Django 4.2.6 on 2023-10-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone_no', models.IntegerField(default=0)),
                ('desc', models.TextField()),
            ],
        ),
    ]
